name: Docker CD Pipeline

on:
  workflow_run:
    workflows: ["Docker CI Pipeline"]
    types:
      - completed

env:
  IMAGE_USER: adiadev
  IMAGE_NAME: fractal-portal
  IMAGE_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the Docker image
        run: sudo docker pull ${{env.IMAGE_USER}}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
      - name: Purge old container
        run: sudo docker rm -f ${{env.IMAGE_NAME}} || true
      - name: Run the Docker image
        run: sudo docker run -d -p 8080:8080 --name ${{env.IMAGE_NAME}} ${{env.IMAGE_USER}}/${{env.IMAGE_NAME}}
