name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_NAME: portal-fractal
  IMAGE_VERSION: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t ${{env.IMAGE_NAME}}:latest

      - name: Push the image to DockerHub
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
